RepublicMonolith/PunditPolicyShouldHaveShowCheck:
  Include:
    - "**/policies/**/*"

RepublicMonolith/GQLTypesShouldHaveIncludeAuthorization:
  Include:
    - "**/types/**/*"

RepublicMonolith/AvoidKeywordArgumentsInSidekiqWorkers:
  Include:
    - "**/workers/**/*"
