# frozen_string_literal: true
require_relative 'republic_monolith/gql_types_should_have_include_authorization'
require_relative 'republic_monolith/pundit_policy_should_have_scope_class'
require_relative 'republic_monolith/pundit_policy_should_have_show_check'
require_relative 'republic_monolith/avoid_keyword_arguments_in_sidekiq_workers'
