RepublicMonolith/AvoidKeywordArgumentsInSidekiqWorkers:
  Description: 'Sidekiq does not support keyword args.'
  Enabled: true
  VersionAdded: '0.1.4'

RepublicMonolith/GQLTypesShouldHaveIncludeAuthorization:
  Description: 'Every GQL type should have include_authorization method call.'
  Enabled: true
  VersionAdded: '0.1.2'

RepublicMonolith/PunditPolicyShouldHaveScopeClass:
  Description: 'Every Pundit policy should have Scope class.'
  Enabled: info
  VersionAdded: '0.1.5'

RepublicMonolith/PunditPolicyShouldHaveShowCheck:
  Description: 'Every Pundit policy should have show? method.'
  Enabled: true
  VersionAdded: '0.1.1'
